eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false  
#added to not allow this service to registry to servicereg
  
server:
  port: 8761
    